connectors/rocketmq-connect-activemq/src/test/java/org/apache/rocketmq/connect/activemq/connector/ActivemqSourceTaskTest.java
connectors/rocketmq-connect-redis/src/main/java/org/apache/rocketmq/connect/redis/connector/RedisSourceConnector.java

[ISSUE #29]Fix error: ActivemqSourceTaskTest build error

---

.gitignore
rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/utils/FileAndPropertyUtil.java

[ISSUE #32] FileAndPropertyUtil code optimization

---

connectors/rocketmq-connect-activemq/pom.xml
connectors/rocketmq-connect-cassandra/pom.xml
connectors/rocketmq-connect-hudi/pom.xml
connectors/rocketmq-connect-jdbc/pom.xml
connectors/rocketmq-connect-jms/pom.xml
connectors/rocketmq-connect-kafka/pom.xml
connectors/rocketmq-connect-rabbitmq/pom.xml
connectors/rocketmq-connect-redis/pom.xml
connectors/rocketmq-replicator/pom.xml
pom.xml

[ISSUE #43]Update and unify the fastjson version

---

README.md

[ISSUE #49] Update inconsistent parameters of FileSourceConnector and FileSinkConnector in readme.

---

pom.xml
rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/store/PositionStorageReaderImpl.java
rocketmq-connect-runtime/src/test/java/org/apache/rocketmq/connect/runtime/connectorwrapper/testimpl/TestPositionStorageReader.java

[ISSUE #53] update connect api to 0.1.2

---

rocketmq-connect-sample/src/main/java/org/apache/rocketmq/connect/file/FileSourceTask.java

https://github.com/apache/rocketmq-connect/issues/88
XXXX

[ISSUE #88] Fix stackOverflowError exception when in IDE debug

---

connectors/rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/RmqMetaReplicator.java
connectors/rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/RmqSourceReplicator.java
connectors/rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/common/Utils.java
connectors/rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/config/ConfigDefine.java
connectors/rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/config/ConfigUtil.java
connectors/rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/config/RmqConnectorConfig.java
connectors/rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/config/TaskDivideConfig.java
connectors/rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/offset/OffsetSyncStore.java
connectors/rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/strategy/DivideTaskByConsistentHash.java

[ISSUE #40]optimize the code in rocketmq_replicator

---

rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/WorkerDirectTask.java

(https://github.com/apache/rocketmq-connect/issues/90)
XX
XXXX

[ISSUE #90] Fix WorkerDirectTask put position store information lost

---

rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/ConnectController.java

[ISSUE #34] Exception  is never thrown in the method

---

rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/Worker.java
rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/ClusterManagementServiceImpl.java
rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/ConfigManagementServiceImpl.java
rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/OffsetManagementServiceImpl.java
rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/PositionManagementServiceImpl.java
rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/RebalanceImpl.java
rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/utils/ConnectUtil.java

[ISSUES #51] Automatically create clusterStoreTopic connector-cluster-topic.

---

rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/WorkerSourceTask.java

[ISSUE #127]when sync tag or key properties of message, remove the 'connect-ext-' prefix

---

connectors/rocketmq-replicator/pom.xml
connectors/rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/MetaSourceTask.java
connectors/rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/RmqMetaReplicator.java
connectors/rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/RmqSourceReplicator.java
connectors/rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/RmqSourceTask.java
connectors/rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/common/Utils.java
connectors/rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/config/ConfigDefine.java
connectors/rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/config/RmqConnectorConfig.java
connectors/rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/config/TaskDivideConfig.java
connectors/rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/schema/SchemaEnum.java
connectors/rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/strategy/DivideTaskByConsistentHash.java
connectors/rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/strategy/DivideTaskByQueue.java
connectors/rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/strategy/DivideTaskByTopic.java
connectors/rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/strategy/TaskDivideStrategy.java
connectors/rocketmq-replicator/src/test/java/org/apache/rocketmq/replicator/DefaultTaskDivideStrategyTest.java
connectors/rocketmq-replicator/src/test/java/org/apache/rocketmq/replicator/RmqSourceReplicatorTest.java

(https://github.com/apache/rocketmq-connect/issues/116)
replicator adapt to the new connect api
XXXX

[ISSUE #116] replicator adapt to the new connect api

---

connectors/rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/MetaSourceTask.java
connectors/rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/RmqSourceTask.java
connectors/rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/common/Utils.java
connectors/rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/config/ConfigUtil.java

#132
The message content is inconsistent. The message content after synchronization is {"MessageExt": "original message content "}
XX
XXXX

[ISSUE #132]The message content is inconsistent after synchronization

---

connectors/aliyun/rocketmq-connect-dingtalk/pom.xml
connectors/aliyun/rocketmq-connect-fc/pom.xml
connectors/aliyun/rocketmq-connect-mns/pom.xml
connectors/aliyun/rocketmq-connect-rocketmq/pom.xml

update connect api to 0.1.2 in aliyun projects
XX
XXXX

[ISSUE #53]update connect api to 0.1.2

---

connectors/rocketmq-replicator/pom.xml

#132
Keep replicator and Runtime versions of some of the same dependencies the same to prevent conflicts
XX
XXXX

[ISSUE #132]Unified dependency package versions.

---

rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/WorkerSinkTask.java
rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/WorkerSourceTask.java
rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/stats/ConnectStatsManager.java

[ISSUE #124]Some sink /source metric statistics are incorrect

---

connectors/aliyun/rocketmq-connect-mns/src/main/java/org/apache/rocketmq/connect/mns/source/MNSRecordConverImpl.java

[ISSUE #110] Update mns connectRecord data

---

pom.xml
rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/TransformChain.java
rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/WorkerDirectTask.java
rocketmq-connect-sample/src/main/java/org/apache/rocketmq/connect/file/FileSinkTask.java
rocketmq-connect-sample/src/main/java/org/apache/rocketmq/connect/file/FilterTransform.java

[ISSUES #178] upgrade to connect api 0.1.3 #178

---

pom.xml
rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/Worker.java
rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/WorkerSinkTask.java
rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/memory/MemoryConfigManagementServiceImpl.java

升级checkStyle的版本&优化代码格式
修复master代码pull下来后maven编译时checkStyle不过的问题
1.升级maven-checkstyle-plugin版本
2.优化checkStyle不过的代码格式
maven编译通过

build: [ISSUE #211]修复工程编译时checkStyle问题

---

rocketmq-connect-runtime/src/test/java/org/apache/rocketmq/connect/runtime/store/PositionStorageReaderImplTest.java
rocketmq-connect-runtime/src/test/java/org/apache/rocketmq/connect/runtime/store/PositionStorageWriterTest.java

Follow #220 
Add PositionStorageReaderImplTest and PositionStorageWriterTest'
XXXX

[ISSUE #220] Add unit test (store module)

---

rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/config/ConnectorConfig.java
rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/Worker.java
rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/WorkerSinkTask.java
rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/WorkerTask.java

checkAndStopConnectors bug fix
remove sinkTask.flush
removeAndCloseMessageQueue topic bug fix
removeMessageQueues filter the same topic
sinkTaskContext.getPausedQueues().retainAll messageQueues
XXXXX
XX
XXXX

[ISSUE #314] Worker sink task bug fix

---

pom.xml
rocketmq-connect-cli/pom.xml
rocketmq-connect-runtime/pom.xml

Polish the pom file
Polish the pom file
XXXX

[ISSUE #322] Polish the pom file

---

connectors/rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/common/DebeziumTimeTypes.java
rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/Worker.java
rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/WorkerSinkTask.java
rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/WorkerSourceTask.java
rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/RebalanceImpl.java

fixd: oom risk
sink reblance
null point
XXXXX
XX
XXXX

[ISSUE #354] bug fix

---

rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/controller/isolation/DelegatingClassLoader.java
rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/controller/isolation/PluginUtils.java

[ISSUE #377] fix plugin load exception 

---

connectors/aliyun/rocketmq-connect-dingtalk/pom.xml
connectors/aliyun/rocketmq-connect-dingtalk/src/main/java/org/apache/rocketmq/connect/dingtalk/sink/DingTalkSinkConnector.java
connectors/aliyun/rocketmq-connect-dingtalk/src/main/java/org/apache/rocketmq/connect/dingtalk/sink/DingTalkSinkTask.java
connectors/aliyun/rocketmq-connect-dingtalk/src/main/java/org/apache/rocketmq/connect/dingtalk/sink/common/OkHttpUtils.java
connectors/aliyun/rocketmq-connect-dingtalk/src/test/java/org/apache/rocketmq/connect/dingtalk/sink/DingTalkSinkConnectorTest.java

upgrade dingTalkConnector rely open message connector to 0.1.4
XX
XXXX

Fix DingTalkSinkConnector rely open message to 0.1.4

---

rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/Worker.java

[ISSUES #422] redress running status

---

connectors/rocketmq-connect-mongo/pom.xml

Fix issue #434   by update dependency com.alibaba:fastjson:1.2.83 @odbozhou 
XXXXX
XX
XXXX

[ISSUE #434]Fix CVE dependency issue

---

connectors/rocketmq-connect-iotdb/README.md
connectors/rocketmq-connect-iotdb/pom.xml
connectors/rocketmq-connect-iotdb/src/main/java/org/apache/rocketmq/connect/iotdb/config/IotdbConfig.java
connectors/rocketmq-connect-iotdb/src/main/java/org/apache/rocketmq/connect/iotdb/config/IotdbConstant.java
connectors/rocketmq-connect-iotdb/src/main/java/org/apache/rocketmq/connect/iotdb/config/SchemaProcessor.java
connectors/rocketmq-connect-iotdb/src/main/java/org/apache/rocketmq/connect/iotdb/connector/IotdbSourceConnector.java
connectors/rocketmq-connect-iotdb/src/main/java/org/apache/rocketmq/connect/iotdb/connector/IotdbSourceTask.java
connectors/rocketmq-connect-iotdb/src/main/java/org/apache/rocketmq/connect/iotdb/exception/IotdbRuntimeException.java
connectors/rocketmq-connect-iotdb/src/main/java/org/apache/rocketmq/connect/iotdb/replicator/source/DeviceEntity.java
connectors/rocketmq-connect-iotdb/src/main/java/org/apache/rocketmq/connect/iotdb/replicator/source/IotdbQuery.java
connectors/rocketmq-connect-iotdb/src/main/java/org/apache/rocketmq/connect/iotdb/replicator/source/IotdbReplicator.java
connectors/rocketmq-connect-iotdb/src/test/java/org/apache/rocketmq/connect/iotdb/config/IotdbConfigTest.java
connectors/rocketmq-connect-iotdb/src/test/java/org/apache/rocketmq/connect/iotdb/connector/IotdbSourceConnectorTest.java
connectors/rocketmq-connect-iotdb/src/test/java/org/apache/rocketmq/connect/iotdb/connector/IotdbSourceTaskTest.java

Close #392 
Add iotdb source connector
XXXX

[ISSUE #392] Add iotdb source connector

---

connectors/rocketmq-replicator/pom.xml
connectors/rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/ReplicatorSourceTask.java
connectors/rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/config/ReplicatorConnectorConfig.java
connectors/rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/context/UnAckMessage.java
connectors/rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/stats/TpsLimiter.java
rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/common/LoggerName.java
rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/WorkerSinkTaskContext.java
rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/WorkerSourceTaskContext.java
rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/controller/isolation/PluginUtils.java
rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/controller/isolation/PluginWrapper.java
rocketmq-connect-runtime/src/main/resources/logback.xml
rocketmq-connect-runtime/src/test/java/org/apache/rocketmq/connect/runtime/controller/isolation/PluginTest.java

[ISSUE #441] Replicator optimize

---

rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/AbstractConfigManagementService.java

[ISSUE #449] stop connector fail bug fix

---

connectors/rocketmq-replicator/README.md

[ISSUE #453] replicator doc optimize

---

connectors/rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/ReplicatorCheckpointConnector.java
connectors/rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/ReplicatorCheckpointTask.java
connectors/rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/config/ReplicatorConnectorConfig.java
connectors/rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/utils/ReplicatorUtils.java

[ISSUE #456] replicator support checkpoint

---

connectors/rocketmq-connect-debezium/pom.xml
connectors/rocketmq-connect-hudi/pom.xml
connectors/rocketmq-connect-jdbc/pom.xml
connectors/rocketmq-connect-mqtt/pom.xml
connectors/rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/ReplicatorSourceTask.java
metric-exporter/pom.xml
metric-exporter/src/main/java/org/apache/rocketmq/connect/metrics/reporter/RocketMQClientUtil.java
pom.xml
rocketmq-connect-runtime/pom.xml
rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/utils/ConnectUtil.java

[ISSUE #476] Support rocketmq version 4.9.5

---

connectors/rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/ReplicatorSourceTask.java
rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/config/WorkerConfig.java
rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/WorkerSourceTask.java

[ISSUES #479] optimize worker source task

---

rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/utils/FileAndPropertyUtil.java
rocketmq-connect-runtime/src/test/java/org/apache/rocketmq/connect/runtime/utils/FileAndPropertyUtilTest.java

[ISSUES #483] fix worker source task commit offset FileNotFoundException

---

connectors/rocketmq-replicator/README.md
connectors/rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/ReplicatorCheckpointTask.java
connectors/rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/ReplicatorSourceTask.java
distribution/conf/metrics.conf

add replicator checkpoint doc
modify metrics.conf default config
XXXXX
XX
XXXX

[ISSUES #485] add replicator checkpoint doc

---

distribution/conf/connect-distributed.conf
docker/connect/Dockerfile
docker/connect/README.md
docker/connect/build_image.sh
rocketmq-connect-runtime/src/main/resources/connect-distributed.conf
rocketmq-connect-runtime/src/main/resources/connect-standalone.conf

[ISSUES #503] fix docker start bug and docker support replicator

---

README.md
connectors/rocketmq-connect-debezium/rocketmq-connect-debezium-mysql/README.md
connectors/rocketmq-connect-debezium/rocketmq-connect-debezium-postgresql/README.md
connectors/rocketmq-connect-jdbc/README.md

- The package name has changed, the `connector.class` needs to be updated
- update the jdbc sink class name

improve jdbc connector docs

---

README.md
rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/config/SourceConnectorConfig.java
rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/WorkerSourceTask.java
rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/AbstractConfigManagementService.java

[ISSUES #530]
XX
XXXX
- [✅] Make sure there is a [Github issue](https://github.com/apache/rocketmq-connect/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [✅] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [✅] Write a pull request …

[ISSUES #530] fix order message bug
